# Dependencies
markdown:            redcarpet #kramdown
highlighter:         pygments
excerpt_separator:   <!--more-->

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               codesalat
tagline:             'nerdig dressing'
description:         '2 Nerds bloggen über Trail & Error Analytics und Quick & Dirty Coding.'
url:                 http://codesalat.de
baseurl:             /
paginate:            5
paginate_path:       'page:num'

# About/contact
author:
  name:              Dirk Adler
  url:               https://klitsche.de
  email:             dirx@klitsche.de

# Custom vars
version:             1.0.0
